encoding: utf-8
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-coffeescrip
remote_theme: benbalter/retlab
title: MarketLeader
description: Attorney, open source developer, product manager
